version: '3.8'

volumes:
   ginecology-data:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /home/scortizo/data-mysql/
   ginecology-backup:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /home/scortizo/data-mysql-backup/
   cache: null
   
services:
   ginecology-database:
      image: ginecology-database:1.0.6
      networks:
        - proxynet
      environment:
      - MYSQL_ONETIME_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=*J+8huv4gRQW
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=#F?5NVHrC?44
      - MYSQL_DATABASE=ginecology
      volumes:
      - ./src/main/resources/sql/1-MySQLCreateTables.sql:/docker-entrypoint-initdb.d/1.sql
      - ./src/main/resources/sql/3-MySQLCreateDataProduction.sql:/docker-entrypoint-initdb.d/2.sql
      - ginecology-data:/var/lib/mysql
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

   ginecology-backup:
      image: fradelg/mysql-cron-backup
      networks:
        - proxynet
      depends_on:
      - ginecology-database
      environment:
      - MYSQL_USER=admin
      - MYSQL_PASS=#F?5NVHrC?44
      - MYSQL_DB=ginecology
      - CRON_TIME=0 0 * * *
      - MYSQL_HOST=ginecology-database
      - MYSQL_PORT=3306
      - TIMEOUT=10s
      - INIT_BACKUP=1
      - TZ=Europe/Madrid
      volumes:
      - ginecology-backup:/backup

   ginecology-service:
      image: ginecology-service:1.0.6
      networks:
        - proxynet
      container_name: ginecology-service
      environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://ginecology-database:3306/ginecology?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=#F?5NVHrC?44
      depends_on:
      - ginecology-database
      expose:
      - 8080
      command: mvn -DskipSqlTests=true -f /app/pom.xml clean spring-boot:run
      deploy:
         labels:
           - "traefik.enable=true"
           - "traefik.http.routers.app-rnasa-imedir.rule=Host(`app.rnasa-imedir.udc.es`)"
           - "traefik.http.routers.app-rnasa-imedir.entrypoints=web"
           - "traefik.http.routers.app-rnasa-imedir-secured.rule=Host(`app.rnasa-imedir.udc.es`)"
           - "traefik.http.routers.app-rnasa-imedir-secured.entrypoints=websecure"
           - "traefik.http.routers.app-rnasa-imedir-secured.tls.certresolver=leresolver"
           - "traefik.http.services.app-rnasa-imedir.loadbalancer.server.port=8080"
           - "traefik.http.routers.app-rnasa-imedir.middlewares=app-rnasa-imedir-redirect"
           - "traefik.http.middlewares.app-rnasa-imedir-redirect.redirectscheme.scheme=https"

networks:           
   proxynet:
       external: true
